#!/usr/bin/env ansible-playbook 
---
- hosts: localhost
  connection: local
  vars:
    version: v3.11
    images:
      # OpenShift Basic Images
      - "registry.redhat.io/openshift3/apb-base:{{ version }}"
      - "registry.redhat.io/openshift3/apb-tools:{{ version }}"
      - "registry.redhat.io/openshift3/automation-broker-apb:{{ version }}"
      - "registry.redhat.io/openshift3/csi-attacher:{{ version }}"
      - "registry.redhat.io/openshift3/csi-driver-registrar:{{ version }}"
      - "registry.redhat.io/openshift3/csi-livenessprobe:{{ version }}"
      - "registry.redhat.io/openshift3/csi-provisioner:{{ version }}"
      - "registry.redhat.io/openshift3/grafana:{{ version }}"
      - "registry.redhat.io/openshift3/image-inspector:{{ version }}"
      - "registry.redhat.io/openshift3/local-storage-provisioner:{{ version }}"
      - "registry.redhat.io/openshift3/manila-provisioner:{{ version }}"
      - "registry.redhat.io/openshift3/mariadb-apb:{{ version }}"
      - "registry.redhat.io/openshift3/mediawiki:{{ version }}"
      - "registry.redhat.io/openshift3/mediawiki-apb:{{ version }}"
      - "registry.redhat.io/openshift3/mysql-apb:{{ version }}"
      - "registry.redhat.io/openshift3/ose-ansible:{{ version }}"
      - "registry.redhat.io/openshift3/ose-ansible-service-broker:{{ version }}"
      - "registry.redhat.io/openshift3/ose-cli:{{ version }}"
      - "registry.redhat.io/openshift3/ose-cluster-autoscaler:{{ version }}"
      - "registry.redhat.io/openshift3/ose-cluster-capacity:{{ version }}"
      - "registry.redhat.io/openshift3/ose-cluster-monitoring-operator:{{ version }}"
      - "registry.redhat.io/openshift3/ose-console:{{ version }}"
      - "registry.redhat.io/openshift3/ose-configmap-reloader:{{ version }}"
      - "registry.redhat.io/openshift3/ose-control-plane:{{ version }}"
      - "registry.redhat.io/openshift3/ose-deployer:{{ version }}"
      - "registry.redhat.io/openshift3/ose-descheduler:{{ version }}"
      - "registry.redhat.io/openshift3/ose-docker-builder:{{ version }}"
      - "registry.redhat.io/openshift3/ose-docker-registry:{{ version }}"
      - "registry.redhat.io/openshift3/ose-efs-provisioner:{{ version }}"
      - "registry.redhat.io/openshift3/ose-egress-dns-proxy:{{ version }}"
      - "registry.redhat.io/openshift3/ose-egress-http-proxy:{{ version }}"
      - "registry.redhat.io/openshift3/ose-egress-router:{{ version }}"
      - "registry.redhat.io/openshift3/ose-haproxy-router:{{ version }}"
      - "registry.redhat.io/openshift3/ose-hyperkube:{{ version }}"
      - "registry.redhat.io/openshift3/ose-hypershift:{{ version }}"
      - "registry.redhat.io/openshift3/ose-keepalived-ipfailover:{{ version }}"
      - "registry.redhat.io/openshift3/ose-kube-rbac-proxy:{{ version }}"
      - "registry.redhat.io/openshift3/ose-kube-state-metrics:{{ version }}"
      - "registry.redhat.io/openshift3/ose-metrics-server:{{ version }}"
      - "registry.redhat.io/openshift3/ose-node:{{ version }}"
      - "registry.redhat.io/openshift3/ose-node-problem-detector:{{ version }}"
      - "registry.redhat.io/openshift3/ose-operator-lifecycle-manager:{{ version }}"
      - "registry.redhat.io/openshift3/ose-ovn-kubernetes:{{ version }}"
      - "registry.redhat.io/openshift3/ose-pod:{{ version }}"
      - "registry.redhat.io/openshift3/ose-prometheus-config-reloader:{{ version }}"
      - "registry.redhat.io/openshift3/ose-prometheus-operator:{{ version }}"
      - "registry.redhat.io/openshift3/ose-recycler:{{ version }}"
      - "registry.redhat.io/openshift3/ose-service-catalog:{{ version }}"
      - "registry.redhat.io/openshift3/ose-template-service-broker:{{ version }}"
      - "registry.redhat.io/openshift3/ose-tests:{{ version }}"
      - "registry.redhat.io/openshift3/ose-web-console:{{ version }}"
      - "registry.redhat.io/openshift3/postgresql-apb:{{ version }}"
      - "registry.redhat.io/openshift3/registry-console:{{ version }}"
      - "registry.redhat.io/openshift3/snapshot-controller:{{ version }}"
      - "registry.redhat.io/openshift3/snapshot-provisioner:{{ version }}"
      - "registry.redhat.io/rhel7/etcd:3.2.22"
      # 
      - "registry.redhat.io/openshift3/ose-efs-provisioner:{{ version }}"
      # 
      - "registry.redhat.io/openshift3/metrics-cassandra:{{ version }}"
      - "registry.redhat.io/openshift3/metrics-hawkular-metrics:{{ version }}"
      - "registry.redhat.io/openshift3/metrics-hawkular-openshift-agent:{{ version }}"
      - "registry.redhat.io/openshift3/metrics-heapster:{{ version }}"
      - "registry.redhat.io/openshift3/metrics-schema-installer:{{ version }}"
      - "registry.redhat.io/openshift3/oauth-proxy:{{ version }}"
      - "registry.redhat.io/openshift3/ose-logging-curator5:{{ version }}"
      - "registry.redhat.io/openshift3/ose-logging-elasticsearch5:{{ version }}"
      - "registry.redhat.io/openshift3/ose-logging-eventrouter:{{ version }}"
      - "registry.redhat.io/openshift3/ose-logging-fluentd:{{ version }}"
      - "registry.redhat.io/openshift3/ose-logging-kibana5:{{ version }}"
      - "registry.redhat.io/openshift3/prometheus:{{ version }}"
      - "registry.redhat.io/openshift3/prometheus-alert-buffer:{{ version }}"
      - "registry.redhat.io/openshift3/prometheus-alertmanager:{{ version }}"
      - "registry.redhat.io/openshift3/prometheus-node-exporter:{{ version }}"
      - "registry.redhat.io/cloudforms46/cfme-openshift-postgresql"
      - "registry.redhat.io/cloudforms46/cfme-openshift-memcached"
      - "registry.redhat.io/cloudforms46/cfme-openshift-app-ui"
      - "registry.redhat.io/cloudforms46/cfme-openshift-app"
      - "registry.redhat.io/cloudforms46/cfme-openshift-embedded-ansible"
      - "registry.redhat.io/cloudforms46/cfme-openshift-httpd"
      - "registry.redhat.io/cloudforms46/cfme-httpd-configmap-generator"
      - "registry.redhat.io/rhgs3/rhgs-server-rhel7"
      - "registry.redhat.io/rhgs3/rhgs-volmanager-rhel7"
      - "registry.redhat.io/rhgs3/rhgs-gluster-block-prov-rhel7"
      - "registry.redhat.io/rhgs3/rhgs-s3-server-rhel7"
      # Source to images stuff
      - "registry.redhat.io/jboss-amq-6/amq63-openshift:latest"
      - "registry.redhat.io/jboss-datagrid-7/datagrid71-openshift:latest"
      - "registry.redhat.io/jboss-datagrid-7/datagrid71-client-openshift:latest"
      - "registry.redhat.io/jboss-datavirt-6/datavirt63-openshift:latest"
      - "registry.redhat.io/jboss-datavirt-6/datavirt63-driver-openshift:latest"
      - "registry.redhat.io/jboss-decisionserver-6/decisionserver64-openshift:latest"
      - "registry.redhat.io/jboss-processserver-6/processserver64-openshift:latest"
      - "registry.redhat.io/jboss-eap-6/eap64-openshift:latest"
      - "registry.redhat.io/jboss-eap-7/eap71-openshift:latest"
      - "registry.redhat.io/jboss-webserver-3/webserver31-tomcat7-openshift:latest"
      - "registry.redhat.io/jboss-webserver-3/webserver31-tomcat8-openshift:latest"
      - "registry.redhat.io/openshift3/jenkins-2-rhel7:{{ version }}"
      - "registry.redhat.io/openshift3/jenkins-agent-maven-35-rhel7:{{ version }}"
      - "registry.redhat.io/openshift3/jenkins-agent-nodejs-8-rhel7:{{ version }}"
      - "registry.redhat.io/openshift3/jenkins-slave-base-rhel7:{{ version }}"
      - "registry.redhat.io/openshift3/jenkins-slave-maven-rhel7:{{ version }}"
      - "registry.redhat.io/openshift3/jenkins-slave-nodejs-rhel7:{{ version }}"
      - "registry.redhat.io/rhscl/mongodb-32-rhel7:latest"
      - "registry.redhat.io/rhscl/mysql-57-rhel7:latest"
      - "registry.redhat.io/rhscl/perl-524-rhel7:latest"
      - "registry.redhat.io/rhscl/php-56-rhel7:latest"
      - "registry.redhat.io/rhscl/postgresql-95-rhel7:latest"
      - "registry.redhat.io/rhscl/python-35-rhel7:latest"
      - "registry.redhat.io/redhat-sso-7/sso70-openshift:latest"
      - "registry.redhat.io/rhscl/ruby-24-rhel7:latest"
      - "registry.redhat.io/redhat-openjdk-18/openjdk18-openshift:latest"
      - "registry.redhat.io/redhat-sso-7/sso71-openshift:latest"
      - "registry.redhat.io/rhscl/nodejs-6-rhel7:latest"
      - "registry.redhat.io/rhscl/mariadb-101-rhel7:latest"

  tasks:
    - name: Enable & Start docker
      service:
        name: docker
        enabled: yes
        state: started
    - name: Pull images
      command: "docker pull {{ item }}"
      with_items: "{{ images }}"